<a href="https://colab.research.google.com/github/patternproject/p.PakistanAI-BootCamp/blob/Week-3/MyAttempt/numpy_v1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Revision History

*   v1: Learning Numpy
*   V2: Loading IRIS dataset and playing with it
*   V3: Continued on V2
*   V4: Able to try the logic on single value of iris dataset
*   V5: More experiments
*   V6: able to solve it with numpy (do not know, about the one loop solution)
*   V7: More experiments
*   V8: More experiments using np.tile 


In [0]:
import numpy as np
import math
import pandas as pd
import tools as t # set of tools for plotting, data splitting, etc..

In [0]:
p1 = np.array([1,2])
p2 = np.array([3,4])

In [0]:
distance = math.sqrt( ((p1[0]-p2[0])**2)+((p1[1]-p2[1])**2) )

In [106]:
print(distance)

2.8284271247461903


In [107]:
 # Calculating distance 
math.sqrt(math.pow(p1[0] - p2[0], 2) + math.pow(p1[1] - p2[1], 2) ) 

2.8284271247461903

In [0]:
def my_f(p1,p2):
  return (math.sqrt(math.pow(p1 - p2,2)))

In [0]:
#my_f(p1,p2)

In [110]:
p1-p2

array([-2, -2])

In [0]:
dist = np.linalg.norm(p1-p2)

In [112]:
print(dist)

2.8284271247461903


In [0]:
def setup(n):
    a = np.random.rand(n, 3)
    b = np.random.rand(n, 3)
    out0 = np.array([a, b])
    out1 = np.array([a.T, b.T])
    return out0, out1

In [0]:
setup = setup

In [115]:
setup

<function __main__.setup>

In [116]:
setup

<function __main__.setup>

In [117]:
setup(1)

(array([[[0.50388124, 0.58775438, 0.86890342]],
 
        [[0.26937063, 0.25854842, 0.21261543]]]), array([[[0.50388124],
         [0.58775438],
         [0.86890342]],
 
        [[0.26937063],
         [0.25854842],
         [0.21261543]]]))

SRC: https://stackoverflow.com/questions/1401712/how-can-the-euclidean-distance-be-calculated-with-numpy

In [0]:
def linalg_norm(data):
    a, b = data[0]
    return numpy.linalg.norm(a - b, axis=1)


def linalg_norm_T(data):
    a, b = data[1]
    return numpy.linalg.norm(a - b, axis=0)


def sqrt_sum(data):
    a, b = data[0]
    return numpy.sqrt(numpy.sum((a - b) ** 2, axis=1))


def sqrt_sum_T(data):
    a, b = data[1]
    return numpy.sqrt(numpy.sum((a - b) ** 2, axis=0))


In [0]:
#a

In [0]:
a,b = setup(1)

In [121]:
a

array([[[0.8667574 , 0.74114939, 0.8336257 ]],

       [[0.11243479, 0.00724804, 0.10526531]]])

In [122]:
b

array([[[0.8667574 ],
        [0.74114939],
        [0.8336257 ]],

       [[0.11243479],
        [0.00724804],
        [0.10526531]]])

In [123]:
a.shape, b.shape

((2, 1, 3), (2, 3, 1))

In [124]:
p1

array([1, 2])

In [125]:
p2

array([3, 4])

In [126]:
np.linalg.norm(p1-p2)

2.8284271247461903

Trying to reduce the no of rows passed to KNN Class

let's read the same data and see how to break it apart

In [127]:
data=pd.read_csv('./iris.data')
data.columns=['SepalLength','SepalWidth','PetalLength','PetalWidth','Class']
print(data.describe())

       SepalLength  SepalWidth  PetalLength  PetalWidth
count   149.000000  149.000000   149.000000  149.000000
mean      5.848322    3.051007     3.774497    1.205369
std       0.828594    0.433499     1.759651    0.761292
min       4.300000    2.000000     1.000000    0.100000
25%       5.100000    2.800000     1.600000    0.300000
50%       5.800000    3.000000     4.400000    1.300000
75%       6.400000    3.300000     5.100000    1.800000
max       7.900000    4.400000     6.900000    2.500000


In [0]:
# Get your data in matrix
X=np.asarray(data[['SepalLength','SepalWidth','PetalLength','PetalWidth']].dropna())

In [129]:
print(X)

[[4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.9 1.5]
 [5.5 2.3 4.

In [130]:
print(X.shape)

(149, 4)


In [0]:
Y=np.asarray(data['Class'].dropna())

In [132]:
print(Y.shape)

(149,)


In [133]:
print(Y)

['Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versic

In [0]:
Xtrain,Ytrain,Xtest,Ytest=t.split_data(X,Y)

In [135]:
print(Xtrain)

[[5.4 3.9 1.3 0.4]
 [5.7 3.8 1.7 0.3]
 [5.4 3.7 1.5 0.2]
 [5.2 4.1 1.5 0.1]
 [4.8 3.1 1.6 0.2]
 [5.1 3.7 1.5 0.4]
 [5.  3.  1.6 0.2]
 [4.8 3.4 1.6 0.2]
 [5.4 3.4 1.7 0.2]
 [5.  3.2 1.2 0.2]
 [4.6 3.1 1.5 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.6 1.4 0.2]
 [5.1 3.5 1.4 0.3]
 [5.4 3.9 1.7 0.4]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.2 3.4 1.4 0.2]
 [4.6 3.6 1.  0.2]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [4.3 3.  1.1 0.1]
 [5.7 4.4 1.5 0.4]
 [4.9 3.  1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [4.6 3.4 1.4 0.3]
 [5.4 3.4 1.5 0.4]
 [5.2 3.5 1.5 0.2]
 [5.  3.4 1.6 0.4]
 [5.  3.4 1.5 0.2]
 [4.7 3.2 1.6 0.2]
 [4.5 2.3 1.3 0.3]
 [5.1 3.8 1.9 0.4]
 [5.1 3.8 1.6 0.2]
 [5.  2.  3.5 1. ]
 [6.6 3.  4.4 1.4]
 [5.8 2.6 4.  1.2]
 [6.7 3.  5.  1.7]
 [6.4 3.2 4.5 1.5]
 [6.  2.7 5.1 1.6]
 [5.2 2.7 3.9 1.4]
 [5.5 2.3 4.  1.3]
 [5.4 3.  4.5 1.5]
 [5.5 2.5 4.  1.3]
 [5.7 3.  4.2 1.2]
 [6.2 2.9 4.3 1.3]
 [6.1 2.8 4.  1.3]
 [5.5 2.6 4.4 1.2]
 [6.  2.2 4.  1. ]
 [5.6 2.5 3.9 1.1]
 [5.9 3.  4.2 1.5]
 [6.1 2.9 4.7 1.4]
 [6.3 2.5 4.

In [136]:
print(Xtrain.shape)

(104, 4)


In [137]:
print(Xtest.shape)

(45, 4)


In [0]:
# Lets train a Decision Tree Classifier on Petal Length and Width
feat=[0,1]

In [139]:
Xtrain[feat]

array([[5.4, 3.9, 1.3, 0.4],
       [5.7, 3.8, 1.7, 0.3]])

In [0]:
#Xtrain[,feat]

In [141]:
Xtrain[:,feat]

array([[5.4, 3.9],
       [5.7, 3.8],
       [5.4, 3.7],
       [5.2, 4.1],
       [4.8, 3.1],
       [5.1, 3.7],
       [5. , 3. ],
       [4.8, 3.4],
       [5.4, 3.4],
       [5. , 3.2],
       [4.6, 3.1],
       [4.9, 3.1],
       [5. , 3.6],
       [5.1, 3.5],
       [5.4, 3.9],
       [4.4, 2.9],
       [4.9, 3.1],
       [5.2, 3.4],
       [4.6, 3.6],
       [4.4, 3.2],
       [5. , 3.5],
       [4.3, 3. ],
       [5.7, 4.4],
       [4.9, 3. ],
       [4.9, 3.1],
       [4.6, 3.4],
       [5.4, 3.4],
       [5.2, 3.5],
       [5. , 3.4],
       [5. , 3.4],
       [4.7, 3.2],
       [4.5, 2.3],
       [5.1, 3.8],
       [5.1, 3.8],
       [5. , 2. ],
       [6.6, 3. ],
       [5.8, 2.6],
       [6.7, 3. ],
       [6.4, 3.2],
       [6. , 2.7],
       [5.2, 2.7],
       [5.5, 2.3],
       [5.4, 3. ],
       [5.5, 2.5],
       [5.7, 3. ],
       [6.2, 2.9],
       [6.1, 2.8],
       [5.5, 2.6],
       [6. , 2.2],
       [5.6, 2.5],
       [5.9, 3. ],
       [6.1, 2.9],
       [6.3,

In [142]:
Xtrain[2,feat]

array([5.4, 3.7])

In [0]:
Xtemp_train = Xtrain[:5,feat]

In [0]:
Xtemp_test = Xtest[:5,feat]

In [145]:
print(Xtemp_train)

[[5.4 3.9]
 [5.7 3.8]
 [5.4 3.7]
 [5.2 4.1]
 [4.8 3.1]]


In [146]:
Xtemp_train.shape

(5, 2)

In [147]:
print(Xtemp_test)

[[5.8 4. ]
 [5.1 3.3]
 [5.1 3.4]
 [5.5 4.2]
 [5.  3.5]]


In [148]:
Xtemp_train.shape

(5, 2)

In [0]:
Xtemp_train.size
Xtemp_train.shape
Xtemp_train.shape[0]
Xtemp_test.shape[0]
#np.zeros((5,5))

dists = np.zeros((Xtemp_train.shape[0],Xtemp_test.shape[0]))

In [0]:

def two_loops(a1,a2):
  first_dim = a1.shape[0]
  second_dim = a2.shape[0]

  for i in range(first_dim):
    for j in range(second_dim):
      dists[i,j] = np.linalg.norm(a1[i]-a2[j])


  return dists

In [0]:
d = two_loops(Xtemp_train,Xtemp_test)

In [152]:
print(d)

[[0.41231056 0.67082039 0.58309519 0.31622777 0.56568542]
 [0.2236068  0.78102497 0.72111026 0.4472136  0.76157731]
 [0.5        0.5        0.42426407 0.50990195 0.4472136 ]
 [0.60827625 0.80622577 0.70710678 0.31622777 0.63245553]
 [1.3453624  0.36055513 0.42426407 1.30384048 0.4472136 ]]


In [153]:
np.linalg.norm(Xtemp_train[0,] - Xtemp_test[0,])

0.41231056256176557

In [154]:
Xtemp_train[0,]

array([5.4, 3.9])

In [155]:
Xtemp_test[0,]

array([5.8, 4. ])

In [156]:
Xtemp_test[0,].shape

(2,)

In [157]:
Xtemp_train[0,] - Xtemp_test[0,]

array([-0.4, -0.1])

In [0]:
my_t = Xtemp_train[0,] - Xtemp_test[0,]

In [159]:
my_t[0]

-0.39999999999999947

In [160]:
my_t[1]

-0.10000000000000009

In [161]:
math.pow(my_t[0],2)

0.1599999999999996

In [162]:
math.pow(my_t[1],2)

0.010000000000000018

In [163]:
math.pow(my_t[0],2) + math.pow(my_t[1],2)

0.1699999999999996

In [164]:
math.sqrt(math.pow(my_t[0],2) + math.pow(my_t[1],2))

0.41231056256176557

In [165]:
d[0,0]

0.41231056256176557

if condition returns True, then nothing happens:

In [166]:
math.sqrt(math.pow(my_t[0],2) + math.pow(my_t[1],2)) == d[0,0]

True

testing out np.meshgrid()

In [0]:
a = np.array([1,2])
b = np.array([3,4])

In [0]:
c,dg = np.meshgrid(a,b)

In [169]:
c

array([[1, 2],
       [1, 2]])

In [170]:
dg

array([[3, 3],
       [4, 4]])

In [0]:
c,dk = np.meshgrid(b,a)

In [172]:
c

array([[3, 4],
       [3, 4]])

In [173]:
dk

array([[1, 1],
       [2, 2]])

Trying to get one-loop distance thing working

In [0]:
Xtemp = Xtemp_train - Xtemp_test

In [175]:
Xtemp

array([[-0.4, -0.1],
       [ 0.6,  0.5],
       [ 0.3,  0.3],
       [-0.3, -0.1],
       [-0.2, -0.4]])

In [176]:
Xtemp.shape

(5, 2)

In [177]:
# using np.pow instead of math.pow

Xtemp2 = np.power(Xtemp,2)

Xtemp2

array([[0.16, 0.01],
       [0.36, 0.25],
       [0.09, 0.09],
       [0.09, 0.01],
       [0.04, 0.16]])

In [178]:
Xtemp3 = np.sum(Xtemp2,axis=1)

Xtemp3

array([0.17, 0.61, 0.18, 0.1 , 0.2 ])

In [179]:
Xtemp4 = np.sqrt(Xtemp3)

Xtemp4

array([0.41231056, 0.78102497, 0.42426407, 0.31622777, 0.4472136 ])

In [180]:
Xtemp4[0]

0.41231056256176557

In [181]:
Xtemp4[0] == d[0,0]

True

In [182]:
Xtemp4[0] - d[0,0]

0.0

In [183]:
d[0,0]

0.41231056256176557

In [184]:
math.sqrt(math.pow(my_t[0],2) + math.pow(my_t[1],2))

0.41231056256176557

In [185]:
d

array([[0.41231056, 0.67082039, 0.58309519, 0.31622777, 0.56568542],
       [0.2236068 , 0.78102497, 0.72111026, 0.4472136 , 0.76157731],
       [0.5       , 0.5       , 0.42426407, 0.50990195, 0.4472136 ],
       [0.60827625, 0.80622577, 0.70710678, 0.31622777, 0.63245553],
       [1.3453624 , 0.36055513, 0.42426407, 1.30384048, 0.4472136 ]])

In [0]:
Too_train = Xtrain[:1,feat]

In [187]:
Too_train.shape

(1, 2)

In [188]:
Too_train

array([[5.4, 3.9]])

In [0]:
Too_test = Xtest[:1,feat]

In [190]:
Too_test.shape

(1, 2)

In [191]:
Too_test

array([[5.8, 4. ]])

In [0]:
Too_1 = Too_train - Too_test

In [193]:
Too_1.shape

(1, 2)

In [194]:
Too_1

array([[-0.4, -0.1]])

In [0]:
Too_2 = np.power(Too_1,2)

In [196]:
Too_2.shape

(1, 2)

In [197]:
Too_2

array([[0.16, 0.01]])

In [0]:
Too_3 = np.sum(Too_2,axis=1)

In [199]:
Too_3.shape

(1,)

In [200]:
Too_3

array([0.17])

In [0]:
Too_4 = np.sqrt(Too_3)

In [202]:
Too_4.shape

(1,)

In [203]:
Too_4[0]

0.41231056256176557

Using Tiling now

In [0]:
Cho_test = Xtemp_test[:2,feat]

In [211]:
Cho_test.shape

(2, 2)

In [212]:
Cho_test

array([[5.8, 4. ],
       [5.1, 3.3]])

In [0]:
Cho_train = Xtemp_train[:2,feat]

In [214]:
Cho_train.shape

(2, 2)

In [215]:
Cho_train

array([[5.4, 3.9],
       [5.7, 3.8]])

In [0]:
Cho_index = Cho_train.shape[0]

In [217]:
Cho_index

2

In [0]:
Cho_test_tiled = np.tile(Cho_test, (Cho_index,1))

In [224]:
Cho_test_tiled

array([[5.8, 4. ],
       [5.1, 3.3],
       [5.8, 4. ],
       [5.1, 3.3]])

In [228]:
for i in range(Cho_index):
  print(Cho_train[i])
  print(Cho_test_tiled[i])
  print(Cho_train[i] - Cho_test_tiled[i])
  print("----")

[5.4 3.9]
[5.8 4. ]
[-0.4 -0.1]
----
[5.7 3.8]
[5.1 3.3]
[0.6 0.5]
----


In [0]:
Cho_tile_index = Cho_test_tiled.shape[0]

In [230]:
print(Cho_tile_index)

4


In [231]:
for i in range(Cho_tile_index):
  print(Cho_train[i])
  print(Cho_test_tiled[i])
  print(Cho_train[i] - Cho_test_tiled[i])
  print("----")

[5.4 3.9]
[5.8 4. ]
[-0.4 -0.1]
----
[5.7 3.8]
[5.1 3.3]
[0.6 0.5]
----


IndexError: ignored

In [232]:
for i in range(Cho_tile_index):
  print(Cho_train[i])
  print(Cho_test_tiled[i])
  print(Cho_train[i] - Cho_test_tiled)
  print("----")

[5.4 3.9]
[5.8 4. ]
[[-0.4 -0.1]
 [ 0.3  0.6]
 [-0.4 -0.1]
 [ 0.3  0.6]]
----
[5.7 3.8]
[5.1 3.3]
[[-0.1 -0.2]
 [ 0.6  0.5]
 [-0.1 -0.2]
 [ 0.6  0.5]]
----


IndexError: ignored

In [233]:
for i in range(Cho_index):
  print(Cho_train[i])
  print(Cho_test_tiled[i])
  print(Cho_train[i] - Cho_test_tiled)
  print("----")

[5.4 3.9]
[5.8 4. ]
[[-0.4 -0.1]
 [ 0.3  0.6]
 [-0.4 -0.1]
 [ 0.3  0.6]]
----
[5.7 3.8]
[5.1 3.3]
[[-0.1 -0.2]
 [ 0.6  0.5]
 [-0.1 -0.2]
 [ 0.6  0.5]]
----


In [234]:
for i in range(Cho_index):
  print(Cho_train[i])
  print(Cho_test_tiled)
  print(Cho_train[i] - Cho_test_tiled)
  print("----")

[5.4 3.9]
[[5.8 4. ]
 [5.1 3.3]
 [5.8 4. ]
 [5.1 3.3]]
[[-0.4 -0.1]
 [ 0.3  0.6]
 [-0.4 -0.1]
 [ 0.3  0.6]]
----
[5.7 3.8]
[[5.8 4. ]
 [5.1 3.3]
 [5.8 4. ]
 [5.1 3.3]]
[[-0.1 -0.2]
 [ 0.6  0.5]
 [-0.1 -0.2]
 [ 0.6  0.5]]
----


In [235]:
for i in range(Cho_index):
  print(Cho_train[i])
  print(Cho_test)
  print(Cho_train[i] - Cho_test)
  print("----")

[5.4 3.9]
[[5.8 4. ]
 [5.1 3.3]]
[[-0.4 -0.1]
 [ 0.3  0.6]]
----
[5.7 3.8]
[[5.8 4. ]
 [5.1 3.3]]
[[-0.1 -0.2]
 [ 0.6  0.5]]
----


In [0]:
for i in range(Cho_index):
  print(Cho_train[i])
  print(Cho_test)
  print(Cho_train[i] - Cho_test)
  print("----")
  np.sum(np.square(Ch_train[i] - Cho_test),axis=1)