<a href="https://colab.research.google.com/github/patternproject/p.PakistanAI-BootCamp/blob/Week-3/MyAttempt/numpy_v1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Revision History

*   v1: Learning Numpy
*   V2: Loading IRIS dataset and playing with it
*   V3: Continued on V2
*   V4: Able to try the logic on single value of iris dataset
*   V5: More experiments
*   V6: able to solve it with numpy (do not know, about the one loop solution)
*   V7: More experiments
*   V8: More experiments using np.tile 
*   V9: Minor Changes
*   V10: Minor Changes
*   V11: Looks done with one loop

In [0]:
import numpy as np
import math
import pandas as pd
import tools as t # set of tools for plotting, data splitting, etc..

In [0]:
p1 = np.array([1,2])
p2 = np.array([3,4])

In [0]:
distance = math.sqrt( ((p1[0]-p2[0])**2)+((p1[1]-p2[1])**2) )

In [239]:
print(distance)

2.8284271247461903


In [240]:
 # Calculating distance 
math.sqrt(math.pow(p1[0] - p2[0], 2) + math.pow(p1[1] - p2[1], 2) ) 

2.8284271247461903

In [0]:
def my_f(p1,p2):
  return (math.sqrt(math.pow(p1 - p2,2)))

In [0]:
#my_f(p1,p2)

In [243]:
p1-p2

array([-2, -2])

In [0]:
dist = np.linalg.norm(p1-p2)

In [245]:
print(dist)

2.8284271247461903


In [0]:
def setup(n):
    a = np.random.rand(n, 3)
    b = np.random.rand(n, 3)
    out0 = np.array([a, b])
    out1 = np.array([a.T, b.T])
    return out0, out1

In [0]:
setup = setup

In [248]:
setup

<function __main__.setup>

In [249]:
setup

<function __main__.setup>

In [250]:
setup(1)

(array([[[0.58792152, 0.72335909, 0.68269428]],
 
        [[0.9170929 , 0.53605036, 0.64329976]]]), array([[[0.58792152],
         [0.72335909],
         [0.68269428]],
 
        [[0.9170929 ],
         [0.53605036],
         [0.64329976]]]))

SRC: https://stackoverflow.com/questions/1401712/how-can-the-euclidean-distance-be-calculated-with-numpy

In [0]:
def linalg_norm(data):
    a, b = data[0]
    return numpy.linalg.norm(a - b, axis=1)


def linalg_norm_T(data):
    a, b = data[1]
    return numpy.linalg.norm(a - b, axis=0)


def sqrt_sum(data):
    a, b = data[0]
    return numpy.sqrt(numpy.sum((a - b) ** 2, axis=1))


def sqrt_sum_T(data):
    a, b = data[1]
    return numpy.sqrt(numpy.sum((a - b) ** 2, axis=0))


In [0]:
#a

In [0]:
a,b = setup(1)

In [254]:
a

array([[[0.56640675, 0.9903965 , 0.34084118]],

       [[0.92687983, 0.29603067, 0.04864387]]])

In [255]:
b

array([[[0.56640675],
        [0.9903965 ],
        [0.34084118]],

       [[0.92687983],
        [0.29603067],
        [0.04864387]]])

In [256]:
a.shape, b.shape

((2, 1, 3), (2, 3, 1))

In [257]:
p1

array([1, 2])

In [258]:
p2

array([3, 4])

In [259]:
np.linalg.norm(p1-p2)

2.8284271247461903

Trying to reduce the no of rows passed to KNN Class

let's read the same data and see how to break it apart

In [260]:
data=pd.read_csv('./iris.data')
data.columns=['SepalLength','SepalWidth','PetalLength','PetalWidth','Class']
print(data.describe())

       SepalLength  SepalWidth  PetalLength  PetalWidth
count   149.000000  149.000000   149.000000  149.000000
mean      5.848322    3.051007     3.774497    1.205369
std       0.828594    0.433499     1.759651    0.761292
min       4.300000    2.000000     1.000000    0.100000
25%       5.100000    2.800000     1.600000    0.300000
50%       5.800000    3.000000     4.400000    1.300000
75%       6.400000    3.300000     5.100000    1.800000
max       7.900000    4.400000     6.900000    2.500000


In [0]:
# Get your data in matrix
X=np.asarray(data[['SepalLength','SepalWidth','PetalLength','PetalWidth']].dropna())

In [262]:
print(X)

[[4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.9 1.5]
 [5.5 2.3 4.

In [263]:
print(X.shape)

(149, 4)


In [0]:
Y=np.asarray(data['Class'].dropna())

In [265]:
print(Y.shape)

(149,)


In [266]:
print(Y)

['Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versic

In [0]:
Xtrain,Ytrain,Xtest,Ytest=t.split_data(X,Y)

In [268]:
print(Xtrain)

[[5.  3.4 1.6 0.4]
 [4.7 3.2 1.3 0.2]
 [4.3 3.  1.1 0.1]
 [5.1 3.3 1.7 0.5]
 [4.6 3.6 1.  0.2]
 [5.  3.4 1.5 0.2]
 [4.9 3.  1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.3 1.4 0.2]
 [5.  3.5 1.3 0.3]
 [5.3 3.7 1.5 0.2]
 [5.5 3.5 1.3 0.2]
 [5.  3.2 1.2 0.2]
 [5.1 3.7 1.5 0.4]
 [4.8 3.  1.4 0.1]
 [5.1 3.8 1.5 0.3]
 [5.  3.  1.6 0.2]
 [4.8 3.  1.4 0.3]
 [5.1 3.4 1.5 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.1 3.8 1.9 0.4]
 [4.4 3.  1.3 0.2]
 [5.2 4.1 1.5 0.1]
 [5.4 3.4 1.5 0.4]
 [5.2 3.4 1.4 0.2]
 [4.4 3.2 1.3 0.2]
 [4.8 3.4 1.6 0.2]
 [5.1 3.8 1.6 0.2]
 [5.4 3.9 1.7 0.4]
 [5.2 3.5 1.5 0.2]
 [5.7 4.4 1.5 0.4]
 [5.8 4.  1.2 0.2]
 [4.6 3.4 1.4 0.3]
 [5.7 3.  4.2 1.2]
 [5.1 2.5 3.  1.1]
 [5.9 3.2 4.8 1.8]
 [5.9 3.  4.2 1.5]
 [6.7 3.1 4.4 1.4]
 [5.5 2.4 3.7 1. ]
 [5.6 3.  4.5 1.5]
 [6.2 2.2 4.5 1.5]
 [7.  3.2 4.7 1.4]
 [6.  2.9 4.5 1.5]
 [5.5 2.3 4.  1.3]
 [5.8 2.6 4.  1.2]
 [6.6 3.  4.4 1.4]
 [5.  2.3 3.3 1. ]
 [6.  3.4 4.5 1.6]
 [5.6 2.7 4.2 1.3]
 [6.3 2.5 4.9 1.5]
 [5.6 2.9 3.6 1.3]
 [5.8 2.7 4.

In [269]:
print(Xtrain.shape)

(104, 4)


In [270]:
print(Xtest.shape)

(45, 4)


In [0]:
# Lets train a Decision Tree Classifier on Petal Length and Width
feat=[0,1]

In [272]:
Xtrain[feat]

array([[5. , 3.4, 1.6, 0.4],
       [4.7, 3.2, 1.3, 0.2]])

In [0]:
#Xtrain[,feat]

In [274]:
Xtrain[:,feat]

array([[5. , 3.4],
       [4.7, 3.2],
       [4.3, 3. ],
       [5.1, 3.3],
       [4.6, 3.6],
       [5. , 3.4],
       [4.9, 3. ],
       [4.9, 3.1],
       [5. , 3.3],
       [5. , 3.5],
       [5.3, 3.7],
       [5.5, 3.5],
       [5. , 3.2],
       [5.1, 3.7],
       [4.8, 3. ],
       [5.1, 3.8],
       [5. , 3. ],
       [4.8, 3. ],
       [5.1, 3.4],
       [4.7, 3.2],
       [4.8, 3.1],
       [5.1, 3.8],
       [4.4, 3. ],
       [5.2, 4.1],
       [5.4, 3.4],
       [5.2, 3.4],
       [4.4, 3.2],
       [4.8, 3.4],
       [5.1, 3.8],
       [5.4, 3.9],
       [5.2, 3.5],
       [5.7, 4.4],
       [5.8, 4. ],
       [4.6, 3.4],
       [5.7, 3. ],
       [5.1, 2.5],
       [5.9, 3.2],
       [5.9, 3. ],
       [6.7, 3.1],
       [5.5, 2.4],
       [5.6, 3. ],
       [6.2, 2.2],
       [7. , 3.2],
       [6. , 2.9],
       [5.5, 2.3],
       [5.8, 2.6],
       [6.6, 3. ],
       [5. , 2.3],
       [6. , 3.4],
       [5.6, 2.7],
       [6.3, 2.5],
       [5.6, 2.9],
       [5.8,

In [275]:
Xtrain[2,feat]

array([4.3, 3. ])

In [0]:
Xtemp_train = Xtrain[:5,feat]

In [0]:
Xtemp_test = Xtest[:5,feat]

In [278]:
print(Xtemp_train)

[[5.  3.4]
 [4.7 3.2]
 [4.3 3. ]
 [5.1 3.3]
 [4.6 3.6]]


In [279]:
Xtemp_train.shape

(5, 2)

In [280]:
print(Xtemp_test)

[[4.9 3.1]
 [5.4 3.7]
 [5.4 3.9]
 [4.8 3.4]
 [5.1 3.5]]


In [281]:
Xtemp_train.shape

(5, 2)

In [0]:
Xtemp_train.size
Xtemp_train.shape
Xtemp_train.shape[0]
Xtemp_test.shape[0]
#np.zeros((5,5))

dists = np.zeros((Xtemp_train.shape[0],Xtemp_test.shape[0]))

In [0]:

def two_loops(a1,a2):
  first_dim = a1.shape[0]
  second_dim = a2.shape[0]

  for i in range(first_dim):
    for j in range(second_dim):
      dists[i,j] = np.linalg.norm(a1[i]-a2[j])


  return dists

In [0]:
d = two_loops(Xtemp_train,Xtemp_test)

In [285]:
print(d)

[[0.31622777 0.5        0.64031242 0.2        0.14142136]
 [0.2236068  0.86023253 0.98994949 0.2236068  0.5       ]
 [0.60827625 1.30384048 1.42126704 0.64031242 0.94339811]
 [0.28284271 0.5        0.67082039 0.31622777 0.2       ]
 [0.58309519 0.80622577 0.85440037 0.28284271 0.50990195]]


In [286]:
np.linalg.norm(Xtemp_train[0,] - Xtemp_test[0,])

0.31622776601683766

In [287]:
Xtemp_train[0,]

array([5. , 3.4])

In [288]:
Xtemp_test[0,]

array([4.9, 3.1])

In [289]:
Xtemp_test[0,].shape

(2,)

In [290]:
Xtemp_train[0,] - Xtemp_test[0,]

array([0.1, 0.3])

In [0]:
my_t = Xtemp_train[0,] - Xtemp_test[0,]

In [292]:
my_t[0]

0.09999999999999964

In [293]:
my_t[1]

0.2999999999999998

In [294]:
math.pow(my_t[0],2)

0.009999999999999929

In [295]:
math.pow(my_t[1],2)

0.0899999999999999

In [296]:
math.pow(my_t[0],2) + math.pow(my_t[1],2)

0.09999999999999983

In [297]:
math.sqrt(math.pow(my_t[0],2) + math.pow(my_t[1],2))

0.31622776601683766

In [298]:
d[0,0]

0.31622776601683766

if condition returns True, then nothing happens:

In [299]:
math.sqrt(math.pow(my_t[0],2) + math.pow(my_t[1],2)) == d[0,0]

True

testing out np.meshgrid()

In [0]:
a = np.array([1,2])
b = np.array([3,4])

In [0]:
c,dg = np.meshgrid(a,b)

In [302]:
c

array([[1, 2],
       [1, 2]])

In [303]:
dg

array([[3, 3],
       [4, 4]])

In [0]:
c,dk = np.meshgrid(b,a)

In [305]:
c

array([[3, 4],
       [3, 4]])

In [306]:
dk

array([[1, 1],
       [2, 2]])

Trying to get one-loop distance thing working

In [0]:
Xtemp = Xtemp_train - Xtemp_test

In [308]:
Xtemp

array([[ 0.1,  0.3],
       [-0.7, -0.5],
       [-1.1, -0.9],
       [ 0.3, -0.1],
       [-0.5,  0.1]])

In [309]:
Xtemp.shape

(5, 2)

In [310]:
# using np.pow instead of math.pow

Xtemp2 = np.power(Xtemp,2)

Xtemp2

array([[0.01, 0.09],
       [0.49, 0.25],
       [1.21, 0.81],
       [0.09, 0.01],
       [0.25, 0.01]])

In [311]:
Xtemp3 = np.sum(Xtemp2,axis=1)

Xtemp3

array([0.1 , 0.74, 2.02, 0.1 , 0.26])

In [312]:
Xtemp4 = np.sqrt(Xtemp3)

Xtemp4

array([0.31622777, 0.86023253, 1.42126704, 0.31622777, 0.50990195])

In [313]:
Xtemp4[0]

0.31622776601683766

In [314]:
Xtemp4[0] == d[0,0]

True

In [315]:
Xtemp4[0] - d[0,0]

0.0

In [316]:
d[0,0]

0.31622776601683766

In [317]:
math.sqrt(math.pow(my_t[0],2) + math.pow(my_t[1],2))

0.31622776601683766

In [318]:
d

array([[0.31622777, 0.5       , 0.64031242, 0.2       , 0.14142136],
       [0.2236068 , 0.86023253, 0.98994949, 0.2236068 , 0.5       ],
       [0.60827625, 1.30384048, 1.42126704, 0.64031242, 0.94339811],
       [0.28284271, 0.5       , 0.67082039, 0.31622777, 0.2       ],
       [0.58309519, 0.80622577, 0.85440037, 0.28284271, 0.50990195]])

In [0]:
Too_train = Xtrain[:1,feat]

In [320]:
Too_train.shape

(1, 2)

In [321]:
Too_train

array([[5. , 3.4]])

In [0]:
Too_test = Xtest[:1,feat]

In [323]:
Too_test.shape

(1, 2)

In [324]:
Too_test

array([[4.9, 3.1]])

In [0]:
Too_1 = Too_train - Too_test

In [326]:
Too_1.shape

(1, 2)

In [327]:
Too_1

array([[0.1, 0.3]])

In [0]:
Too_2 = np.power(Too_1,2)

In [329]:
Too_2.shape

(1, 2)

In [330]:
Too_2

array([[0.01, 0.09]])

In [0]:
Too_3 = np.sum(Too_2,axis=1)

In [332]:
Too_3.shape

(1,)

In [333]:
Too_3

array([0.1])

In [0]:
Too_4 = np.sqrt(Too_3)

In [335]:
Too_4.shape

(1,)

In [336]:
Too_4[0]

0.31622776601683766

Using Tiling now

In [0]:
Cho_test = Xtemp_test[:2,feat]

In [338]:
Cho_test.shape

(2, 2)

In [339]:
Cho_test

array([[4.9, 3.1],
       [5.4, 3.7]])

In [0]:
Cho_train = Xtemp_train[:2,feat]

In [341]:
Cho_train.shape

(2, 2)

In [342]:
Cho_train

array([[5. , 3.4],
       [4.7, 3.2]])

In [0]:
Cho_index = Cho_train.shape[0]

In [344]:
Cho_index

2

In [0]:
Cho_test_tiled = np.tile(Cho_test, (Cho_index,1))

In [346]:
Cho_test_tiled

array([[4.9, 3.1],
       [5.4, 3.7],
       [4.9, 3.1],
       [5.4, 3.7]])

In [347]:
for i in range(Cho_index):
  print(Cho_train[i])
  print(Cho_test_tiled[i])
  print(Cho_train[i] - Cho_test_tiled[i])
  print("----")

[5.  3.4]
[4.9 3.1]
[0.1 0.3]
----
[4.7 3.2]
[5.4 3.7]
[-0.7 -0.5]
----


In [0]:
Cho_tile_index = Cho_test_tiled.shape[0]

In [349]:
print(Cho_tile_index)

4


In [351]:
'''
for i in range(Cho_tile_index):
  print(Cho_train[i])
  print(Cho_test_tiled[i])
  print(Cho_train[i] - Cho_test_tiled[i])
  print("----")
'''

'\nfor i in range(Cho_tile_index):\n  print(Cho_train[i])\n  print(Cho_test_tiled[i])\n  print(Cho_train[i] - Cho_test_tiled[i])\n  print("----")\n'

In [352]:
for i in range(Cho_tile_index):
  print(Cho_train[i])
  print(Cho_test_tiled[i])
  print(Cho_train[i] - Cho_test_tiled)
  print("----")

[5.  3.4]
[4.9 3.1]
[[ 0.1  0.3]
 [-0.4 -0.3]
 [ 0.1  0.3]
 [-0.4 -0.3]]
----
[4.7 3.2]
[5.4 3.7]
[[-0.2  0.1]
 [-0.7 -0.5]
 [-0.2  0.1]
 [-0.7 -0.5]]
----


IndexError: ignored

In [353]:
for i in range(Cho_index):
  print(Cho_train[i])
  print(Cho_test_tiled[i])
  print(Cho_train[i] - Cho_test_tiled)
  print("----")

[5.  3.4]
[4.9 3.1]
[[ 0.1  0.3]
 [-0.4 -0.3]
 [ 0.1  0.3]
 [-0.4 -0.3]]
----
[4.7 3.2]
[5.4 3.7]
[[-0.2  0.1]
 [-0.7 -0.5]
 [-0.2  0.1]
 [-0.7 -0.5]]
----


In [354]:
for i in range(Cho_index):
  print(Cho_train[i])
  print(Cho_test_tiled)
  print(Cho_train[i] - Cho_test_tiled)
  print("----")

[5.  3.4]
[[4.9 3.1]
 [5.4 3.7]
 [4.9 3.1]
 [5.4 3.7]]
[[ 0.1  0.3]
 [-0.4 -0.3]
 [ 0.1  0.3]
 [-0.4 -0.3]]
----
[4.7 3.2]
[[4.9 3.1]
 [5.4 3.7]
 [4.9 3.1]
 [5.4 3.7]]
[[-0.2  0.1]
 [-0.7 -0.5]
 [-0.2  0.1]
 [-0.7 -0.5]]
----


In [355]:
for i in range(Cho_index):
  print(Cho_train[i])
  print(Cho_test)
  print(Cho_train[i] - Cho_test)
  print("----")

[5.  3.4]
[[4.9 3.1]
 [5.4 3.7]]
[[ 0.1  0.3]
 [-0.4 -0.3]]
----
[4.7 3.2]
[[4.9 3.1]
 [5.4 3.7]]
[[-0.2  0.1]
 [-0.7 -0.5]]
----


In [369]:

Cho_train_index = Cho_train.shape[0]

Cho_train_index

2

In [370]:
Cho_test_index = Cho_test.shape[0]
Cho_test_index

2

In [372]:
#result = np.zeros(Cho_index)



cho_dists = np.zeros((Cho_train_index, Cho_test_index))
cho_dists.shape

(2, 2)

In [373]:
for i in range(Cho_index):
  print(Cho_train[i])
  print(Cho_test)
  print(Cho_train[i] - Cho_test)
  print("----")
  cho_dists[i,:] = np.sqrt(np.sum(np.square(Cho_train[i] - Cho_test),axis=1))


[5.  3.4]
[[4.9 3.1]
 [5.4 3.7]]
[[ 0.1  0.3]
 [-0.4 -0.3]]
----
[4.7 3.2]
[[4.9 3.1]
 [5.4 3.7]]
[[-0.2  0.1]
 [-0.7 -0.5]]
----


In [374]:
cho_dists

array([[0.31622777, 0.5       ],
       [0.2236068 , 0.86023253]])