<a href="https://colab.research.google.com/github/patternproject/p.PakistanAI-BootCamp/blob/Week-3/MyAttempt/numpy_v1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Revision History

*   v1: Learning Numpy
*   V2: Loading IRIS dataset and playing with it
*   V3: Continued on V2
*   V4: Able to try the logic on single value of iris dataset
*   V5: More experiments



In [0]:
import numpy as np
import math
import pandas as pd
import tools as t # set of tools for plotting, data splitting, etc..

In [0]:
p1 = np.array([1,2])
p2 = np.array([3,4])

In [0]:
distance = math.sqrt( ((p1[0]-p2[0])**2)+((p1[1]-p2[1])**2) )

In [4]:
print(distance)

2.8284271247461903


In [5]:
 # Calculating distance 
math.sqrt(math.pow(p1[0] - p2[0], 2) + math.pow(p1[1] - p2[1], 2) ) 

2.8284271247461903

In [0]:
def my_f(p1,p2):
  return (math.sqrt(math.pow(p1 - p2,2)))

In [7]:
#my_f(p1,p2)

TypeError: ignored

In [0]:
p1-p2

In [0]:
dist = np.linalg.norm(p1-p2)

In [0]:
print(dist)

In [0]:
def setup(n):
    a = np.random.rand(n, 3)
    b = np.random.rand(n, 3)
    out0 = np.array([a, b])
    out1 = np.array([a.T, b.T])
    return out0, out1

In [0]:
setup = setup

In [0]:
setup

In [0]:
setup

In [0]:
setup(1)

SRC: https://stackoverflow.com/questions/1401712/how-can-the-euclidean-distance-be-calculated-with-numpy

In [0]:
def linalg_norm(data):
    a, b = data[0]
    return numpy.linalg.norm(a - b, axis=1)


def linalg_norm_T(data):
    a, b = data[1]
    return numpy.linalg.norm(a - b, axis=0)


def sqrt_sum(data):
    a, b = data[0]
    return numpy.sqrt(numpy.sum((a - b) ** 2, axis=1))


def sqrt_sum_T(data):
    a, b = data[1]
    return numpy.sqrt(numpy.sum((a - b) ** 2, axis=0))


In [0]:
a

In [0]:
a,b = setup(1)

In [0]:
a

In [0]:
b

In [0]:
a.shape, b.shape

In [0]:
p1

In [0]:
p2

In [0]:
np.linalg.norm(p1-p2)

Trying to reduce the no of rows passed to KNN Class

let's read the same data and see how to break it apart

In [0]:
data=pd.read_csv('./iris.data')
data.columns=['SepalLength','SepalWidth','PetalLength','PetalWidth','Class']
print(data.describe())

In [0]:
# Get your data in matrix
X=np.asarray(data[['SepalLength','SepalWidth','PetalLength','PetalWidth']].dropna())

In [0]:
print(X)

In [0]:
print(X.shape)

In [0]:
Y=np.asarray(data['Class'].dropna())

In [0]:
print(Y.shape)

In [0]:
print(Y)

In [0]:
Xtrain,Ytrain,Xtest,Ytest=t.split_data(X,Y)

In [0]:
print(Xtrain)

In [0]:
print(Xtrain.shape)

In [0]:
print(Xtest.shape)

In [0]:
# Lets train a Decision Tree Classifier on Petal Length and Width
feat=[0,1]

In [0]:
Xtrain[feat]

In [0]:
Xtrain[,feat]

In [0]:
Xtrain[:,feat]

In [0]:
Xtrain[2,feat]

In [0]:
Xtemp_train = Xtrain[:5,feat]

In [0]:
Xtemp_test = Xtest[:5,feat]

In [0]:
print(Xtemp_train)

In [0]:
print(Xtemp_test)

In [0]:
Xtemp_train.size
Xtemp_train.shape
Xtemp_train.shape[0]
Xtemp_test.shape[0]
#np.zeros((5,5))

dists = np.zeros((Xtemp_train.shape[0],Xtemp_test.shape[0]))

In [0]:

def two_loops(a1,a2):
  first_dim = a1.shape[0]
  second_dim = a2.shape[0]

  for i in range(first_dim):
    for j in range(second_dim):
      dists[i,j] = np.linalg.norm(a1[i]-a2[j])


  return dists

In [0]:
d = two_loops(Xtemp_train,Xtemp_test)

In [0]:
print(d)

In [0]:
np.linalg.norm(Xtemp_train[0,] - Xtemp_test[0,])

In [0]:
Xtemp_train[0,]

In [0]:
Xtemp_test[0,]

In [0]:
Xtemp_test[0,].shape

In [0]:
Xtemp_train[0,] - Xtemp_test[0,]

In [0]:
my_t = Xtemp_train[0,] - Xtemp_test[0,]

In [0]:
my_t[0]

In [0]:
my_t[1]

In [0]:
math.sqrt(math.pow(my_t[0],2) + math.pow(my_t[1],2))

In [0]:
d[0,0]

if condition returns True, then nothing happens:

In [0]:
math.sqrt(math.pow(my_t[0],2) + math.pow(my_t[1],2)) == d[0,0]

testing out np.meshgrid()

In [0]:
a = np.array([1,2])
b = np.array([3,4])

In [0]:
c,d = np.meshgrid(a,b)

In [16]:
c

array([[1, 2],
       [1, 2]])

In [17]:
d

array([[3, 3],
       [4, 4]])

In [0]:
c,d = np.meshgrid(b,a)

In [19]:
c

array([[3, 4],
       [3, 4]])

In [20]:
d

array([[1, 1],
       [2, 2]])