<a href="https://colab.research.google.com/github/patternproject/p.PakistanAI-BootCamp/blob/Week-3/MyAttempt/numpy_v1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Revision History

*   v1: Learning Numpy
*   V2: Loading IRIS dataset and playing with it
*   V3: Continued on V2
*   V4: Able to try the logic on single value of iris dataset



In [0]:
import numpy as np
import math
import pandas as pd
import tools as t # set of tools for plotting, data splitting, etc..

In [0]:
p1 = np.array([1,2])
p2 = np.array([3,4])

In [0]:
distance = math.sqrt( ((p1[0]-p2[0])**2)+((p1[1]-p2[1])**2) )

In [7]:
print(distance)

2.8284271247461903


In [9]:
 # Calculating distance 
math.sqrt(math.pow(p1[0] - p2[0], 2) + math.pow(p1[1] - p2[1], 2) ) 

2.8284271247461903

In [0]:
def my_f(p1,p2):
  return (math.sqrt(math.pow(p1 - p2,2)))

In [13]:
my_f(p1,p2)

TypeError: ignored

In [14]:
p1-p2

array([-2, -2])

In [0]:
dist = np.linalg.norm(p1-p2)

In [17]:
print(dist)

2.8284271247461903


In [0]:
def setup(n):
    a = np.random.rand(n, 3)
    b = np.random.rand(n, 3)
    out0 = np.array([a, b])
    out1 = np.array([a.T, b.T])
    return out0, out1

In [0]:
setup = setup

In [20]:
setup

<function __main__.setup>

In [21]:
setup

<function __main__.setup>

In [24]:
setup(1)

(array([[[0.95849134, 0.08792642, 0.04677609]],
 
        [[0.44648981, 0.26559254, 0.61228534]]]), array([[[0.95849134],
         [0.08792642],
         [0.04677609]],
 
        [[0.44648981],
         [0.26559254],
         [0.61228534]]]))

SRC: https://stackoverflow.com/questions/1401712/how-can-the-euclidean-distance-be-calculated-with-numpy

In [0]:
def linalg_norm(data):
    a, b = data[0]
    return numpy.linalg.norm(a - b, axis=1)


def linalg_norm_T(data):
    a, b = data[1]
    return numpy.linalg.norm(a - b, axis=0)


def sqrt_sum(data):
    a, b = data[0]
    return numpy.sqrt(numpy.sum((a - b) ** 2, axis=1))


def sqrt_sum_T(data):
    a, b = data[1]
    return numpy.sqrt(numpy.sum((a - b) ** 2, axis=0))


In [26]:
a

array([1, 2])

In [0]:
a,b = setup(1)

In [28]:
a

array([[[0.47271323, 0.35026109, 0.4297344 ]],

       [[0.9382958 , 0.96237702, 0.05143486]]])

In [29]:
b

array([[[0.47271323],
        [0.35026109],
        [0.4297344 ]],

       [[0.9382958 ],
        [0.96237702],
        [0.05143486]]])

In [32]:
a.shape, b.shape

((2, 1, 3), (2, 3, 1))

In [33]:
p1

array([1, 2])

In [34]:
p2

array([3, 4])

In [36]:
np.linalg.norm(p1-p2)

2.8284271247461903

Trying to reduce the no of rows passed to KNN Class

let's read the same data and see how to break it apart

In [38]:
data=pd.read_csv('./iris.data')
data.columns=['SepalLength','SepalWidth','PetalLength','PetalWidth','Class']
print(data.describe())

       SepalLength  SepalWidth  PetalLength  PetalWidth
count   149.000000  149.000000   149.000000  149.000000
mean      5.848322    3.051007     3.774497    1.205369
std       0.828594    0.433499     1.759651    0.761292
min       4.300000    2.000000     1.000000    0.100000
25%       5.100000    2.800000     1.600000    0.300000
50%       5.800000    3.000000     4.400000    1.300000
75%       6.400000    3.300000     5.100000    1.800000
max       7.900000    4.400000     6.900000    2.500000


In [0]:
# Get your data in matrix
X=np.asarray(data[['SepalLength','SepalWidth','PetalLength','PetalWidth']].dropna())

In [40]:
print(X)

[[4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.9 1.5]
 [5.5 2.3 4.

In [48]:
print(X.shape)

(149, 4)


In [0]:
Y=np.asarray(data['Class'].dropna())

In [49]:
print(Y.shape)

(149,)


In [42]:
print(Y)

['Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versic

In [0]:
Xtrain,Ytrain,Xtest,Ytest=t.split_data(X,Y)

In [47]:
print(Xtrain)

[[4.4 3.2 1.3 0.2]
 [4.6 3.4 1.4 0.3]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.3 0.2]
 [5.2 4.1 1.5 0.1]
 [5.  3.4 1.5 0.2]
 [5.4 3.4 1.5 0.4]
 [4.8 3.  1.4 0.3]
 [5.4 3.9 1.7 0.4]
 [5.1 3.7 1.5 0.4]
 [5.1 3.3 1.7 0.5]
 [5.5 4.2 1.4 0.2]
 [5.  3.2 1.2 0.2]
 [4.7 3.2 1.6 0.2]
 [4.5 2.3 1.3 0.3]
 [4.8 3.4 1.6 0.2]
 [5.8 4.  1.2 0.2]
 [5.1 3.8 1.9 0.4]
 [5.5 3.5 1.3 0.2]
 [4.8 3.1 1.6 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.5 1.6 0.6]
 [4.6 3.2 1.4 0.2]
 [5.  3.4 1.6 0.4]
 [4.3 3.  1.1 0.1]
 [5.7 3.8 1.7 0.3]
 [5.4 3.4 1.7 0.2]
 [4.9 3.  1.4 0.2]
 [5.7 4.4 1.5 0.4]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.1 3.5 1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [5.2 3.5 1.5 0.2]
 [4.9 2.4 3.3 1. ]
 [5.6 2.9 3.6 1.3]
 [5.1 2.5 3.  1.1]
 [6.2 2.9 4.3 1.3]
 [6.  2.9 4.5 1.5]
 [5.7 2.8 4.5 1.3]
 [6.5 2.8 4.6 1.5]
 [6.4 2.9 4.3 1.3]
 [6.3 2.5 4.9 1.5]
 [6.7 3.1 4.4 1.4]
 [5.7 2.9 4.2 1.3]
 [6.  2.2 4.  1. ]
 [5.6 3.  4.1 1.3]
 [6.9 3.1 4.9 1.5]
 [5.  2.  3.5 1. ]
 [5.4 3.  4.5 1.5]
 [5.5 2.4 3.7 1. ]
 [6.1 2.8 4.  1.3]
 [5.8 2.7 4.

In [50]:
print(Xtrain.shape)

(104, 4)


In [51]:
print(Xtest.shape)

(45, 4)


In [0]:
# Lets train a Decision Tree Classifier on Petal Length and Width
feat=[0,1]

In [52]:
Xtrain[feat]

array([[4.4, 3.2, 1.3, 0.2],
       [4.6, 3.4, 1.4, 0.3]])

In [53]:
Xtrain[,feat]

SyntaxError: ignored

In [54]:
Xtrain[:,feat]

array([[4.4, 3.2],
       [4.6, 3.4],
       [4.8, 3.4],
       [4.7, 3.2],
       [5.2, 4.1],
       [5. , 3.4],
       [5.4, 3.4],
       [4.8, 3. ],
       [5.4, 3.9],
       [5.1, 3.7],
       [5.1, 3.3],
       [5.5, 4.2],
       [5. , 3.2],
       [4.7, 3.2],
       [4.5, 2.3],
       [4.8, 3.4],
       [5.8, 4. ],
       [5.1, 3.8],
       [5.5, 3.5],
       [4.8, 3.1],
       [5.3, 3.7],
       [5. , 3.5],
       [4.6, 3.2],
       [5. , 3.4],
       [4.3, 3. ],
       [5.7, 3.8],
       [5.4, 3.4],
       [4.9, 3. ],
       [5.7, 4.4],
       [4.4, 2.9],
       [4.9, 3.1],
       [5.1, 3.5],
       [5.1, 3.8],
       [5.2, 3.5],
       [4.9, 2.4],
       [5.6, 2.9],
       [5.1, 2.5],
       [6.2, 2.9],
       [6. , 2.9],
       [5.7, 2.8],
       [6.5, 2.8],
       [6.4, 2.9],
       [6.3, 2.5],
       [6.7, 3.1],
       [5.7, 2.9],
       [6. , 2.2],
       [5.6, 3. ],
       [6.9, 3.1],
       [5. , 2. ],
       [5.4, 3. ],
       [5.5, 2.4],
       [6.1, 2.8],
       [5.8,

In [55]:
Xtrain[2,feat]

array([4.8, 3.4])

In [0]:
Xtemp_train = Xtrain[:5,feat]

In [0]:
Xtemp_test = Xtest[:5,feat]

In [60]:
print(Xtemp_train)

[[4.4 3.2]
 [4.6 3.4]
 [4.8 3.4]
 [4.7 3.2]
 [5.2 4.1]]


In [61]:
print(Xtemp_test)

[[4.6 3.1]
 [4.8 3. ]
 [5.  3.3]
 [4.6 3.6]
 [5.  3.6]]


In [0]:
Xtemp_train.size
Xtemp_train.shape
Xtemp_train.shape[0]
Xtemp_test.shape[0]
#np.zeros((5,5))

dists = np.zeros((Xtemp_train.shape[0],Xtemp_test.shape[0]))

In [0]:

def two_loops(a1,a2):
  first_dim = a1.shape[0]
  second_dim = a2.shape[0]

  for i in range(first_dim):
    for j in range(second_dim):
      dists[i,j] = np.linalg.norm(a1[i]-a2[j])


  return dists

In [0]:
d = two_loops(Xtemp_train,Xtemp_test)

In [83]:
print(d)

[[0.2236068  0.4472136  0.60827625 0.4472136  0.72111026]
 [0.3        0.4472136  0.41231056 0.2        0.4472136 ]
 [0.36055513 0.4        0.2236068  0.28284271 0.28284271]
 [0.14142136 0.2236068  0.31622777 0.41231056 0.5       ]
 [1.16619038 1.17046999 0.82462113 0.78102497 0.53851648]]


In [91]:
np.linalg.norm(Xtemp_train[0,] - Xtemp_test[0,])

0.22360679774997838

In [87]:
Xtemp_train[0,]

array([4.4, 3.2])

In [89]:
Xtemp_test[0,]

array([4.6, 3.1])

In [90]:
Xtemp_test[0,].shape

(2,)

In [92]:
Xtemp_train[0,] - Xtemp_test[0,]

array([-0.2,  0.1])

In [0]:
my_t = Xtemp_train[0,] - Xtemp_test[0,]

In [94]:
my_t[0]

-0.1999999999999993

In [95]:
my_t[1]

0.10000000000000009

In [96]:
math.sqrt(math.pow(my_t[0],2) + math.pow(my_t[1],2))

0.22360679774997838

In [97]:
d[0,0]

0.22360679774997838

if condition returns True, then nothing happens:

In [101]:
math.sqrt(math.pow(my_t[0],2) + math.pow(my_t[1],2)) == d[0,0]

True