<a href="https://colab.research.google.com/github/patternproject/p.PakistanAI-BootCamp/blob/Week-3/MyAttempt/numpy_v1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Revision History

*   v1: Learning Numpy
*   V2: Loading IRIS dataset and playing with it
*   V3: Continued on V2
*   V4: Able to try the logic on single value of iris dataset
*   V5: More experiments
*   V6: able to solve it with numpy (do not know, about the one loop solution)
*   V7: More experiments



In [0]:
import numpy as np
import math
import pandas as pd
import tools as t # set of tools for plotting, data splitting, etc..

In [0]:
p1 = np.array([1,2])
p2 = np.array([3,4])

In [0]:
distance = math.sqrt( ((p1[0]-p2[0])**2)+((p1[1]-p2[1])**2) )

In [24]:
print(distance)

2.8284271247461903


In [25]:
 # Calculating distance 
math.sqrt(math.pow(p1[0] - p2[0], 2) + math.pow(p1[1] - p2[1], 2) ) 

2.8284271247461903

In [0]:
def my_f(p1,p2):
  return (math.sqrt(math.pow(p1 - p2,2)))

In [0]:
#my_f(p1,p2)

In [28]:
p1-p2

array([-2, -2])

In [0]:
dist = np.linalg.norm(p1-p2)

In [30]:
print(dist)

2.8284271247461903


In [0]:
def setup(n):
    a = np.random.rand(n, 3)
    b = np.random.rand(n, 3)
    out0 = np.array([a, b])
    out1 = np.array([a.T, b.T])
    return out0, out1

In [0]:
setup = setup

In [33]:
setup

<function __main__.setup>

In [34]:
setup

<function __main__.setup>

In [35]:
setup(1)

(array([[[0.84873192, 0.55442292, 0.29901447]],
 
        [[0.58277368, 0.73942252, 0.57523784]]]), array([[[0.84873192],
         [0.55442292],
         [0.29901447]],
 
        [[0.58277368],
         [0.73942252],
         [0.57523784]]]))

SRC: https://stackoverflow.com/questions/1401712/how-can-the-euclidean-distance-be-calculated-with-numpy

In [0]:
def linalg_norm(data):
    a, b = data[0]
    return numpy.linalg.norm(a - b, axis=1)


def linalg_norm_T(data):
    a, b = data[1]
    return numpy.linalg.norm(a - b, axis=0)


def sqrt_sum(data):
    a, b = data[0]
    return numpy.sqrt(numpy.sum((a - b) ** 2, axis=1))


def sqrt_sum_T(data):
    a, b = data[1]
    return numpy.sqrt(numpy.sum((a - b) ** 2, axis=0))


In [37]:
a

array([1, 2])

In [0]:
a,b = setup(1)

In [39]:
a

array([[[0.64540225, 0.44061913, 0.80445714]],

       [[0.05298338, 0.97059495, 0.75353255]]])

In [40]:
b

array([[[0.64540225],
        [0.44061913],
        [0.80445714]],

       [[0.05298338],
        [0.97059495],
        [0.75353255]]])

In [41]:
a.shape, b.shape

((2, 1, 3), (2, 3, 1))

In [42]:
p1

array([1, 2])

In [43]:
p2

array([3, 4])

In [44]:
np.linalg.norm(p1-p2)

2.8284271247461903

Trying to reduce the no of rows passed to KNN Class

let's read the same data and see how to break it apart

In [45]:
data=pd.read_csv('./iris.data')
data.columns=['SepalLength','SepalWidth','PetalLength','PetalWidth','Class']
print(data.describe())

       SepalLength  SepalWidth  PetalLength  PetalWidth
count   149.000000  149.000000   149.000000  149.000000
mean      5.848322    3.051007     3.774497    1.205369
std       0.828594    0.433499     1.759651    0.761292
min       4.300000    2.000000     1.000000    0.100000
25%       5.100000    2.800000     1.600000    0.300000
50%       5.800000    3.000000     4.400000    1.300000
75%       6.400000    3.300000     5.100000    1.800000
max       7.900000    4.400000     6.900000    2.500000


In [0]:
# Get your data in matrix
X=np.asarray(data[['SepalLength','SepalWidth','PetalLength','PetalWidth']].dropna())

In [47]:
print(X)

[[4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.9 1.5]
 [5.5 2.3 4.

In [48]:
print(X.shape)

(149, 4)


In [0]:
Y=np.asarray(data['Class'].dropna())

In [50]:
print(Y.shape)

(149,)


In [51]:
print(Y)

['Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa'
 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor'
 'Iris-versicolor' 'Iris-versicolor' 'Iris-versicolor' 'Iris-versic

In [0]:
Xtrain,Ytrain,Xtest,Ytest=t.split_data(X,Y)

In [53]:
print(Xtrain)

[[5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [4.9 3.1 1.5 0.1]
 [4.8 3.  1.4 0.1]
 [5.1 3.7 1.5 0.4]
 [5.7 3.8 1.7 0.3]
 [4.4 3.  1.3 0.2]
 [4.7 3.2 1.6 0.2]
 [5.4 3.7 1.5 0.2]
 [5.8 4.  1.2 0.2]
 [5.  3.4 1.5 0.2]
 [4.8 3.  1.4 0.3]
 [5.5 3.5 1.3 0.2]
 [5.2 3.4 1.4 0.2]
 [5.  3.6 1.4 0.2]
 [5.7 4.4 1.5 0.4]
 [5.  3.2 1.2 0.2]
 [4.4 3.2 1.3 0.2]
 [5.4 3.4 1.7 0.2]
 [4.9 3.1 1.5 0.1]
 [4.6 3.2 1.4 0.2]
 [4.6 3.1 1.5 0.2]
 [5.2 4.1 1.5 0.1]
 [4.4 2.9 1.4 0.2]
 [5.  3.4 1.6 0.4]
 [4.9 3.  1.4 0.2]
 [5.  3.3 1.4 0.2]
 [5.4 3.4 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [4.8 3.1 1.6 0.2]
 [5.2 3.5 1.5 0.2]
 [5.4 3.9 1.3 0.4]
 [4.6 3.4 1.4 0.3]
 [5.4 3.9 1.7 0.4]
 [5.6 2.9 3.6 1.3]
 [5.7 2.9 4.2 1.3]
 [6.4 2.9 4.3 1.3]
 [5.6 3.  4.1 1.3]
 [6.1 2.9 4.7 1.4]
 [5.6 3.  4.5 1.5]
 [6.  2.7 5.1 1.6]
 [5.5 2.4 3.7 1. ]
 [6.8 2.8 4.8 1.4]
 [6.7 3.1 4.7 1.5]
 [5.8 2.7 3.9 1.2]
 [5.8 2.7 4.1 1. ]
 [6.2 2.9 4.3 1.3]
 [5.4 3.  4.5 1.5]
 [6.1 3.  4.6 1.4]
 [6.3 3.3 4.7 1.6]
 [5.8 2.6 4.  1.2]
 [6.3 2.3 4.4 1.3]
 [5.6 2.7 4.

In [54]:
print(Xtrain.shape)

(104, 4)


In [55]:
print(Xtest.shape)

(45, 4)


In [0]:
# Lets train a Decision Tree Classifier on Petal Length and Width
feat=[0,1]

In [57]:
Xtrain[feat]

array([[5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2]])

In [0]:
#Xtrain[,feat]

In [60]:
Xtrain[:,feat]

array([[5.1, 3.3],
       [4.8, 3.4],
       [4.9, 3.1],
       [4.8, 3. ],
       [5.1, 3.7],
       [5.7, 3.8],
       [4.4, 3. ],
       [4.7, 3.2],
       [5.4, 3.7],
       [5.8, 4. ],
       [5. , 3.4],
       [4.8, 3. ],
       [5.5, 3.5],
       [5.2, 3.4],
       [5. , 3.6],
       [5.7, 4.4],
       [5. , 3.2],
       [4.4, 3.2],
       [5.4, 3.4],
       [4.9, 3.1],
       [4.6, 3.2],
       [4.6, 3.1],
       [5.2, 4.1],
       [4.4, 2.9],
       [5. , 3.4],
       [4.9, 3. ],
       [5. , 3.3],
       [5.4, 3.4],
       [4.6, 3.6],
       [4.8, 3.1],
       [5.2, 3.5],
       [5.4, 3.9],
       [4.6, 3.4],
       [5.4, 3.9],
       [5.6, 2.9],
       [5.7, 2.9],
       [6.4, 2.9],
       [5.6, 3. ],
       [6.1, 2.9],
       [5.6, 3. ],
       [6. , 2.7],
       [5.5, 2.4],
       [6.8, 2.8],
       [6.7, 3.1],
       [5.8, 2.7],
       [5.8, 2.7],
       [6.2, 2.9],
       [5.4, 3. ],
       [6.1, 3. ],
       [6.3, 3.3],
       [5.8, 2.6],
       [6.3, 2.3],
       [5.6,

In [61]:
Xtrain[2,feat]

array([4.9, 3.1])

In [0]:
Xtemp_train = Xtrain[:5,feat]

In [0]:
Xtemp_test = Xtest[:5,feat]

In [64]:
print(Xtemp_train)

[[5.1 3.3]
 [4.8 3.4]
 [4.9 3.1]
 [4.8 3. ]
 [5.1 3.7]]


In [90]:
Xtemp_train.shape

(5, 2)

In [65]:
print(Xtemp_test)

[[5.3 3.7]
 [5.  3.5]
 [4.7 3.2]
 [5.1 3.5]
 [5.5 4.2]]


In [92]:
Xtemp_train.shape

(5, 2)

In [0]:
Xtemp_train.size
Xtemp_train.shape
Xtemp_train.shape[0]
Xtemp_test.shape[0]
#np.zeros((5,5))

dists = np.zeros((Xtemp_train.shape[0],Xtemp_test.shape[0]))

In [0]:

def two_loops(a1,a2):
  first_dim = a1.shape[0]
  second_dim = a2.shape[0]

  for i in range(first_dim):
    for j in range(second_dim):
      dists[i,j] = np.linalg.norm(a1[i]-a2[j])


  return dists

In [0]:
d = two_loops(Xtemp_train,Xtemp_test)

In [117]:
print(d)

[[0.4472136  0.2236068  0.41231056 0.2        0.98488578]
 [0.58309519 0.2236068  0.2236068  0.31622777 1.06301458]
 [0.72111026 0.41231056 0.2236068  0.4472136  1.25299641]
 [0.86023253 0.53851648 0.2236068  0.58309519 1.3892444 ]
 [0.2        0.2236068  0.64031242 0.2        0.64031242]]


In [70]:
np.linalg.norm(Xtemp_train[0,] - Xtemp_test[0,])

0.4472135954999583

In [71]:
Xtemp_train[0,]

array([5.1, 3.3])

In [72]:
Xtemp_test[0,]

array([5.3, 3.7])

In [73]:
Xtemp_test[0,].shape

(2,)

In [74]:
Xtemp_train[0,] - Xtemp_test[0,]

array([-0.2, -0.4])

In [0]:
my_t = Xtemp_train[0,] - Xtemp_test[0,]

In [76]:
my_t[0]

-0.20000000000000018

In [77]:
my_t[1]

-0.40000000000000036

In [102]:
math.pow(my_t[0],2)

0.04000000000000007

In [104]:
math.pow(my_t[1],2)

0.16000000000000028

In [105]:
math.pow(my_t[0],2) + math.pow(my_t[1],2)

0.20000000000000034

In [78]:
math.sqrt(math.pow(my_t[0],2) + math.pow(my_t[1],2))

0.4472135954999583

In [79]:
d[0,0]

0.4472135954999583

if condition returns True, then nothing happens:

In [80]:
math.sqrt(math.pow(my_t[0],2) + math.pow(my_t[1],2)) == d[0,0]

True

testing out np.meshgrid()

In [0]:
a = np.array([1,2])
b = np.array([3,4])

In [0]:
c,d = np.meshgrid(a,b)

In [83]:
c

array([[1, 2],
       [1, 2]])

In [84]:
d

array([[3, 3],
       [4, 4]])

In [0]:
c,d = np.meshgrid(b,a)

In [86]:
c

array([[3, 4],
       [3, 4]])

In [87]:
d

array([[1, 1],
       [2, 2]])

Trying to get one-loop distance thing working

In [0]:
Xtemp = Xtemp_train - Xtemp_test

In [89]:
Xtemp

array([[-0.2, -0.4],
       [-0.2, -0.1],
       [ 0.2, -0.1],
       [-0.3, -0.5],
       [-0.4, -0.5]])

In [93]:
Xtemp.shape

(5, 2)

In [101]:
# using np.pow instead of math.pow

Xtemp2 = np.power(Xtemp,2)

Xtemp2

array([[0.04, 0.16],
       [0.04, 0.01],
       [0.04, 0.01],
       [0.09, 0.25],
       [0.16, 0.25]])

In [106]:
Xtemp3 = np.sum(Xtemp2,axis=1)

Xtemp3

array([0.2 , 0.05, 0.05, 0.34, 0.41])

In [108]:
Xtemp4 = np.sqrt(Xtemp3)

Xtemp4

array([0.4472136 , 0.2236068 , 0.2236068 , 0.58309519, 0.64031242])

In [110]:
Xtemp4[0]

0.4472135954999583

In [118]:
Xtemp4[0] == d[0,0]

True

In [112]:
Xtemp4[0] - d[0,0]

-0.5527864045000417

In [119]:
d[0,0]

0.4472135954999583

In [120]:
math.sqrt(math.pow(my_t[0],2) + math.pow(my_t[1],2))

0.4472135954999583

In [121]:
d

array([[0.4472136 , 0.2236068 , 0.41231056, 0.2       , 0.98488578],
       [0.58309519, 0.2236068 , 0.2236068 , 0.31622777, 1.06301458],
       [0.72111026, 0.41231056, 0.2236068 , 0.4472136 , 1.25299641],
       [0.86023253, 0.53851648, 0.2236068 , 0.58309519, 1.3892444 ],
       [0.2       , 0.2236068 , 0.64031242, 0.2       , 0.64031242]])

In [0]:
Too_train = Xtrain[:1,feat]

In [123]:
Too_train.shape

(1, 2)

In [124]:
Too_train

array([[5.1, 3.3]])

In [0]:
Too_test = Xtest[:1,feat]

In [128]:
Too_test.shape

(1, 2)

In [129]:
Too_test

array([[5.3, 3.7]])

In [0]:
Too_1 = Too_train - Too_test

In [132]:
Too_1.shape

(1, 2)

In [133]:
Too_1

array([[-0.2, -0.4]])

In [0]:
Too_2 = np.power(Too_1,2)

In [135]:
Too_2.shape

(1, 2)

In [136]:
Too_2

array([[0.04, 0.16]])

In [0]:
Too_3 = np.sum(Too_2,axis=1)

In [138]:
Too_3.shape

(1,)

In [139]:
Too_3

array([0.2])

In [0]:
Too_4 = np.sqrt(Too_3)

In [141]:
Too_4.shape

(1,)

In [143]:
Too_4[0]

0.4472135954999583