<a href="https://colab.research.google.com/github/patternproject/p.PakistanAI-BootCamp/blob/Week-1/numpy/Practise_v1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Practising NumPy

v2

In [0]:
import numpy as np

In [0]:
a_1 = np.array([1,2])

In [4]:
a_1.shape

(2,)

In [0]:
a_2 = np.arange(1,10)

In [6]:
a_2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
a_2.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [0]:
a_3 = np.linspace(1,10)

In [9]:
a_3

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [0]:
a_4 = np.linspace(1,10,5)

In [11]:
a_4

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])